kind: pipeline
type: docker
name: image builder

steps:
  - name: test
    image: ubuntu:latest
    commands:
    - echo "got here"
    - echo $DRONE_TAG
trigger:
  branch:
  - master
  event:
  - tag 
  - push                  
